spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #Druid连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true


